CREATE DATABASE campusvc;
USE campusvc;

CREATE TABLE cp_user(
  uid INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'UserID', 
  unionid VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户unionid',
  nick_name VARCHAR(32) NOT NULL DEFAULT '' COMMENT '用户昵称',
  avatar VARCHAR(256) NOT NULL DEFAULT '' COMMENT '用户头像',
  cp_role TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户管理员角色',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (uid),
  UNIQUE KEY (unionid)
);

CREATE TABLE cp_sf_user(
  uid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'UserID',
  cur_festid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前火种节ID',
  sf_role TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户火种节管理员角色',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (uid)
);

CREATE TABLE cp_sf_fest(
  festid INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '火种节ID',
  orgerid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '组织者ID',
  title VARCHAR(32) NOT NULL DEFAULT '' COMMENT '火种节标题',
  intro TEXT NOT NULL COMMENT '项目简介',
  stime INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '开始时间',
  etime INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '结束时间',
  addr VARCHAR(64) NOT NULL DEFAULT '' COMMENT '地址',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (festid)
);

CREATE TABLE cp_sf_fest_logo(
  festid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '火种节ID',
  logoid TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '火种节logid',
  url VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'LOGO URL',
  PRIMARY KEY (festid)
);

CREATE TABLE cp_sf_fest_member(
  uid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'UserID',
  festid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '火种节ID',
  fest_role TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户火种节角色',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY (uid, festid)
);

CREATE TABLE cp_sf_proj(
  projid INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  festid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '火种节ID',
  captainid INT NOT NULL DEFAULT 0 COMMENT '创建者ID',
  title VARCHAR(32) NOT NULL DEFAULT '' COMMENT '项目标题',
  intro TEXT NOT NULL COMMENT '项目简介',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (projid),
  KEY (festid)
);

CREATE TABLE cp_sf_proj_prog(
  projid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
  stepid TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '流程ID',
  url VARCHAR(128) NOT NULL DEFAULT '' COMMENT '图片URL',
  content VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '内容',
  UNIQUE KEY(projid, stepid)
);

CREATE TABLE cp_sf_proj_member(
  uid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户ID',
  projid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY (projid, uid)
);

CREATE TABLE cp_sf_proj_cmnt(
  cmntid INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID',
  projid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '项目ID',
  cmntorid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论者ID',
  tscore TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '总体分',
  ascore TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '对人分数',
  bscore TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '对事分数',
  cscore TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '意向分数',
  content TEXT NOT NULL COMMENT '评论内容',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
  PRIMARY KEY (cmntid),
  KEY (projid)
);

CREATE TABLE cp_sf_proj_reply(
  replyid INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '回复ID',
  cmntid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论ID',
  replierid INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '回复者ID',
  content TEXT NOT NULL COMMENT '回复内容',
  ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复时间',
  PRIMARY KEY (replyid),
  KEY (cmntid)
);
